version: "3.7"

services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    command: run
    volumes:
      - ./static:/app/static
    env_file: .env
    ports:
      - 127.0.0.1:8000:8000
    links:
      - db
    depends_on:
      - db

  db:
    container_name: db
    restart: always
    image: postgres:12.4-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file: .env
    expose:
      - 5432
volumes:
  postgres-data: